stages:
  - build
build_project:
  stage: build
  script:
    - xcodebuild clean -project LogKit.xcodeproj -scheme LogKit
    - xcodebuild -project LogKit.xcodeproj -scheme LogKit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' test
