language: objective-c
osx_image: xcode7.3.1
before_script:
- brew update
- brew upgrade
- brew outdated xctool || brew upgrade xctool
script: 
- xctool -scheme LogKit -sdk iphonesimulator build  
- xctool -scheme LogKit -sdk iphonesimulator run-tests