language: objective-c
osx_image: xcode7.3.1
xcode_project: LogKit
xcode_sdk: iphonesimulator9.3.1
env:
- TOOLCHAINS=swift
script:
- swift build --fetch
before_install:
- TOOLCHAIN_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a
- curl -O https://swift.org/builds/development/xcode/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-osx.pkg
- sudo installer -pkg ${TOOLCHAIN_VERSION}-osx.pkg -target /
before_script:
- brew update
- brew upgrade
- brew outdated xctool || brew upgrade xctool
script: 
- xctool -scheme LogKit -sdk iphonesimulator build  
- xctool -scheme LogKit -sdk iphonesimulator run-tests