language: objective-c
osx_image: xcode7.3
before_script:
- brew update
- brew upgrade
- brew outdated xctool || brew upgrade xctool
script: 
- xctool -scheme LogKit -sdk iphonesimulator9.3 build  
- xctool -scheme LogKit -sdk iphonesimulator9.3 run-tests
