language: objective-c
osx_image: xcode7.3.1
xcode_project: LogKit
xcode_sdk: iphonesimulator9.3.1
before_script:
- brew update
- brew upgrade
- brew upgrade xctool
script: 
- xctool -scheme LogKit -sdk iphonesimulator build  
- xctool -scheme LogKit -sdk iphonesimulator run-tests