language: objective-c
osx_image: xcode7.3.1
xcode_project: LogKit
xcode_sdk: iphonesimulator9.3.1
env:
  global: 
    - FRAMEWORK_NAME=LogKit
before_install:
  - brew update
  - brew update || brew upgrade
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --verbose
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
  
 script: xctool -scheme LogKit -sdk iphonesimulator build 
 script: xctool -scheme LogKit -sdk iphonesimulator run-tests